### ISSUE TITLE
Linter-golinter falls

### ISSUE THREAD

**Issue by liferooter** [AtomLinter/linter-golinter#155]
# Software

**Atom:** 1.45.0 x64
**Electron:** 4.2.12
**Chrome:** 69.0.3497.128
**Node:** v10.11.0
**OS:** Arch Linux
**Thrown from:** linter-golinter Atom package 1.3.0

# Steps to reproduce

1. With clean atom (without ~/.atom and ~/.config/Atom directories) install packages:

* linter
* linter-golinter
* linter-linter-ui-default with its dependencies (busy-signal and intentions)

2. Open any .go file, edit it and save it to activate linter. You will have an error.

# Stack trace

```
[Linter] Error running Golint Error: Column start (23) greater than line length (22) for line 6
    at Object.generateRange (/home/gleb/.atom/packages/linter-golinter/node_modules/atom-linter/lib/index.js:181)
    at getMessagesFromStd (/home/gleb/.atom/packages/linter-golinter/lib/main.js:23)
    at /home/gleb/.atom/packages/linter-golinter/lib/main.js:54
(anonymous) @ /home/gleb/.atom/packages/linter/lib/linter-registry.js:154
```

**Comment by Arcanemagus** [comment]
Those errors would be specific to whatever file you are opening, can you provide a file to reproduce this on?

**Comment by liferooter** [comment]
It was just trivial code for print number's square:
```golang
package main

import "fmt"

func main() {
  var a int
  fmt.Println(a * a)
}
```

**Comment by liferooter** [comment]
Sorry for this issue. I've found what causes this bug: it was my path to golint executable: /home/gleb/go/bin/golint. Linter-golinter fall because it's too long. I'm closing this issue.
