### ISSUE TITLE
Not linting on Mac OS X and Atom 1.0.0

### ISSUE THREAD

**Issue by andrefreitas** [AtomLinter/linter-golinter#3]
Even with giving the correct golint path it is not working on OS X and Atom 1.0.0.

**Comment by zhevron** [comment]
Are you receiving any error messages when it's supposed to be linting? What version of the Linter package are you running? Please include the output of `apm list` and any errors you encounter.

**Comment by kavu** [comment]
@andrefreitas could you test it with current version?

**Comment by andrefreitas** [comment]
@kavu it's solved, thank you :)
