### ISSUE TITLE
Linter runs only on file save?

### ISSUE THREAD

**Issue by yukon-sergey** [AtomLinter/linter-golinter#91]
Linter messages only appear when I save my Go source file and not while I'm typing.
I've linter-eslint installed along with linter-golinter and former shows messages while I'm typing.
I've "Lint as you type" enabled in Linter with default settings.
Using latest available versions:

- Atom 1.12.5
- linter 1.11.18
- linter-golinter 1.2.1

![linter-golinter](https://cloud.githubusercontent.com/assets/3583803/20570210/687a8bd8-b1ab-11e6-8dd9-180a987ce06e.gif)

Any ideas?

**Comment by Arcanemagus** [comment]
That's [how it's specified](https://github.com/AtomLinter/linter-golinter/blob/96185045dcd676dc2288cb4ebd00aef943154353/lib/main.js#L77), as the way this linter provider is currently written it can't use the current editor contents.

A lot of the time (like with ESLint) a linter program can be run on contents piped in through `stdin`, but some linters can't handle this, especially ones like `golint` which are actually compiling the code. If you find that `golint` actually _can_ work on `stdin` input, then a PR moving to this model would be great!

I'm marking this as closed, but if you have any other questions feel free to continue the discussion.

**Comment by yukon-sergey** [comment]
Got it, thanks!
