### ISSUE TITLE
Error: Column start greater than line length

### ISSUE THREAD

**Issue by mrkschan** [AtomLinter/linter-golinter#97]
When saving a file with content like this.

```
package main

func main() {
```

This error is shown.

```
Error: Column start (14) greater than line length (13)
    at Object.rangeFromLineNumber (C:\Users\mrkschan\Dropbox\winconf\atom\packages\linter-golinter\node_modules\atom-linter\lib\index.js:179:11)
    at C:/Users/mrkschan/Dropbox/winconf/atom/packages/linter-golinter/lib/main.js:39:31
    at Array.map (native)
    at C:/Users/mrkschan/Dropbox/winconf/atom/packages/linter-golinter/lib/main.js:35:56
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by cdmackay** [comment]
same here.

Atom 1.18.0-beta0
Linter 2.1.4
Linter-golinter 1.2.2

in my go file, line 14 is a blank zero-length line.

In my case, there was a different error in the file:

```
$ ~/go/bin/golint hello.go
hello.go:15:52: expected '}', found 'EOF'

```

and fixing that stopped the golinter error, too.

```
linter-registry.js [sm]:137
[Linter] Error running Golint Error: Column start (51) greater than line length (50) for line 14
    at Object.generateRange (/Users/x/.atom/packages/linter-golinter/node_modules/atom-linter/lib/index.js:177:11)
    at /Users/x/.atom/packages/linter-golinter/lib/main.js:39:31
    at Array.map (native)
    at /Users/x/.atom/packages/linter-golinter/lib/main.js:35:56
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by Arcanemagus** [comment]
@cdmackay The numbers in the error are 0-indexed (like Atom's internal representation), while the numbers you see in the editor and from `golint` are 1-indexed, so "line 14" in the error is line 15 in `golint`'s output. The error is saying that there is only 51 characters on that line, but `golint` is saying there is something wrong on the 5**2**nd character, which doesn't exist.

It's highly likely this is a bug in `golint` that should be reported there.

@mrkschan Took some time to try to reproduce your case, and it's the same bug in `golint`: It's reporting an issue on column 16 of a line that only has 15 columns.

**Comment by cdmackay** [comment]
OK, thanks, but I'm confused: I manually ran golint and it didn't have the problem that occurs when it's run by golinter; see my earlier comment where I show the (correct) output from golint.

What am I missing? thanks again…

**Comment by Arcanemagus** [comment]
@cdmackay You didn't provide the example file so I can't say for sure, but I'm guessing you are hitting the exact same bug that is in the example that @mrkschan posted. The output from `golint` is being parsed correctly by this package, the problem is that it's just plain wrong as it lists a column that doesn't exist.

If you place your cursor in Atom at the end of the line in question I'm guessing it would say you are on column 51, but as you posted `golint` said there was a problem on column 52 which doesn't exist.

**Comment by cdmackay** [comment]
oh! I'm sorry, yes, I see it now. thanks again. I agree it looks like a golint bug.
